name: Accessibility Scanner
on: workflow_dispatch

jobs:
  accessibility_scanner:
    runs-on: ubuntu-latest
    steps:
      - uses: github/accessibility-scanner@v3
        with:
          urls: https://radancy.dev
          repository: radancyco/radancy.github.io
          token: ${{ secrets.GH_TOKEN }}
          cache_key: a11y-scan-v1
